## Common lemon demo properties

# Spring related properties
spring:

  # Active profile
  profiles.active: dev
  
  # JSON serialization settings
  jackson:
    default-property-inclusion: NON_NULL
    
    serialization:
      write-null-map-values: false 
      
    deserialization:
      accept-single-value-as-array: true
  
  devtools:
    # Comment this if you want the app to restart
    # when source code changes
    restart.enabled: false
    livereload.enabled: false

server.session.persistent: false

# Spring Lemon related properties
lemon:

  # First ADMIN user
  admin:
    username: admin@example.com
    password: admin!
    
  # Remember-me secret key
  remember-me-key: someSecret
  
   # Spring Lemon flags
   # enabled:
      # json-prefix: false
      # user-details-service: false
      
  # Properties to be passed to client
  shared:
    fooBar: 123...