## Development environment

spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/lemon?useSSL=false
    username: lemon
    password: lemon
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1011974249454-6gq0hr01gqh3cndoqnss5r69tkk2nd84.apps.googleusercontent.com
            client-secret: saDA6Cj60wipncFM-hzBD-C6
          facebook:
            client-id: 1234020186718741
            client-secret: 0c0abaf685a83e879e8e48b1167c96ab

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security.oauth2.client: DEBUG
    com.naturalprogrammer: DEBUG
  #file: D:\\tmp\\dev-log.txt

lemon:

  cors:
    # Comma separated values of CORS allowedOrigins
    # If this property is not given, CORS is not configured
    allowed-origins: http://localhost:9000
    
  recaptcha:
    sitekey: 6LdwxRcUAAAAABkhOGWQXhl9FsR27D5YUJRuGzx0
    secretkey: 6LdwxRcUAAAAADaG0Eo1qkYCco15cnngiBoBt2IO
    
  # Oauth2 client related properties
  remote-resources:
  -
    id: facebook
    details:
      clientId: 1234020186718741
      clientSecret: 0c0abaf685a83e879e8e48b1167c96ab
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: email
    userInfoUri: https://graph.facebook.com/me?fields=name,email
  -
    id: google
    details:
      clientId: 1011974249454-6gq0hr01gqh3cndoqnss5r69tkk2nd84.apps.googleusercontent.com
      clientSecret: saDA6Cj60wipncFM-hzBD-C6
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: email
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
    
